@hostname = http://localhost:5000/api/users
# {{hostname}}

# REGISTER
POST  {{hostname}}/register
Content-Type: application/json

{
  "handle": "test-handle1",
  "email": "testemail@example.com",
  "password": "test-password",
  "password2": "test-password"
}


###
# LOGIN
POST {{hostname}}/login
Content-Type: application/json

{
  "email": "testemail@example.com",
  "password": "test-password"
}


###
# Protected Route
GET {{hostname}}/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2RiNjQxMjNkZTdhMDk5MzliNjJjMyIsImhhbmRsZSI6InRlc3QtaGFuZGxlMSIsImVtYWlsIjoidGVzdGVtYWlsQGV4YW1wbGUuY29tIiwiaWF0IjoxNjM1OTA0MzczLCJleHAiOjE2MzU5MDc5NzN9.lwfL8vL0cufqweiNhEwefeISxWE_XV8Js_BE2XC-36E

