@hostname = http://localhost:5000/api/users
# {{hostname}}

# REGISTER
POST  {{hostname}}/register
Content-Type: application/json

{
  "handle": "test-handle1",
  "email": "testemail@example.com",
  "password": "test-password",
  "password2": "test-password"
}


###
# LOGIN
POST {{hostname}}/login
Content-Type: application/json

{
  "email": "testemail@example.com",
  "password": "test-password"
}


###
# Protected Route
GET {{hostname}}/current
Content-Type: application/json

{
  "Authorization": ""
}